#!/bin/bash
echo -e "total 20\ndrwxr-xr-x 2 root root 116 Feb  8 13:41 .\ndrwxr-xr-x 4 root root  60 Feb  8 07:15 ..\n-rwxr--r-x 1 root root  79 Feb  8 11:02 0-current_working_directory\n-rwxr--r-x 1 root root  73 Feb  8 11:28 1-listit\n-rwxr--r-x 1 root root  30 Feb  8 12:36 2-bring_me_home\n-rwxr--r-x 1 root root 313 Feb  8 13:41 3-listfiles\n-rwxr--r-x 1 root root 212 Feb  8 11:53 README.m\n"
